- hosts: [terraform-ansible]
  tasks:
    - name: Instalando o Python3, virtualenv
      apt:
        pkg:
        - python3
        - virtualenv
        update_cache: yes
      become: yes 
    - name: Instalando dependencias com pip (Django Rest)
      pip: 
        virtualenv: /home/ubuntu/ro/venv
        name: 
          - django
          - djangorestframework
    - name: Iniciando o projeto
      shell: '. /home/ubuntu/ro/venv/bin/activate; django-admin startproject setup /home/ubuntu/ro'
    - name: Alterando o hosts do settings
      lineinfile: 
        path: /home/ubuntu/ro/setup/settings.py
        regexp: 'ALLOWED_HOSTS'
        line: 'ALLOWED_HOSTS = ["*"]'
        backrefs: yes 